optimization:
  learning_rate: 0.01
  max_iterations: 250
  convergence_threshold: 1.0e-4
  identity_loss_weight: 1.0
  lpips_loss_weight: 0.6
  cross_attn_loss_weight: 10000.0
  self_attn_loss_weight: 100.0
  strength_weights:
    light:
      identity: 0.5
      lpips: 1.0
      cross_attn: 5000.0
      self_attn: 50.0
      max_iterations: 100
    medium:
      identity: 1.0
      lpips: 0.6
      cross_attn: 10000.0
      self_attn: 100.0
      max_iterations: 250
    strong:
      identity: 1.5
      lpips: 0.4
      cross_attn: 15000.0
      self_attn: 150.0
      max_iterations: 350

model:
  stable_diffusion_path: checkpoints/sd2
  flux_path: checkpoints/flux1
  face_models_path: checkpoints/face_models
  sd_model_id: stabilityai/stable-diffusion-2-base
  sd_guidance_scale: 7.5
  sd_num_inference_steps: 50
  flux_model_id: black-forest-labs/FLUX.1-dev
  flux_guidance_scale: 1.0
  flux_num_inference_steps: 28
  arcface_model: buffalo_l
  facenet_model: vggface2

system:
  device: cuda:0
  use_fp16: true
  use_xformers: true
  max_batch_size: 1
  gradient_checkpointing: true
  low_mem: false
  image_size: 512
  output_format: PNG
  log_level: INFO
  log_file: null
  experiment_name: privacy_protection
  results_dir: results
  checkpoint_dir: checkpoints 